### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by kj22594** [DataDog/Miscellany#98]
As python2 has been EOL since Jan 1st 2020 I'm curious if there is any movement to migrating this project to python3?

**Comment by chrpron** [comment]
You can use python3 directly without modifications. Validated by 2to3 script (https://docs.python.org/fr/3.8/library/2to3.html) and tested with Python 3.8.2.

**Comment by misiupajor** [comment]
Hi @kj22594, [Dogmover](https://github.com/DataDog/Miscellany/tree/master/Dogmover) is now migrated to using Python 3. Thanks for your feedback.
